config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users

  scope module: 'admin', path: 'admin' do
    resources :countries
    resources :regions
    resources :places
    resources :accommodation_types
    get "/users", to: "users#index", as: "managers"
    post "/toggle_block_manager/:id", to: "users#toggle_block_manager", as: "toggle_block_manager"
  end

  resources :comments, :except => [:show, :new, :create]
  resources :room_reservations, :only => [:index, :show, :destroy]
  resources :accommodations do
    get "my", on: :collection, as: :my
    post "approve", on: :member, as: :approve
    resources :rooms, on: :member do
      resources :room_reservations, :except => [:index, :edit, :update, :show, :destroy]
    end
    resources :comments, on: :member do
      post "grade", on: :member, as: :grade
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :accommodation
  belongs_to :user

  has_many :grades, :dependent => :destroy

  scope :managed_by, -> (manager) { where(accommodation: { user: manager }) }
  scope :posted_by, -> (user) { where(user: user) }

  def posted_by?(commenter)
    user.id == commenter.id
  end

  def average_grade
    unless grades.count == 0
      sum = grades.inject(0) { |sum, grade| sum + grade.value }
      sum.to_f / grades.count.to_f
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_accommodation
  before_action :set_comment, only: [:edit, :update, :destroy, :show, :grade]

  def index
    @comments =
      if @accommodation.present?
        @accommodation.comments
      else
        if current_user.type == "admin"
          Comment.all
        elsif current_user.type == "manager"
          Comment.managed_by(current_user)
        elsif current_user.type == "user"
          Comment.posted_by(current_user)
        end
      end
  end

  def new
    unless @accommodation.commented_by?(current_user) || current_user.type != "user"
      @comment = Comment.new
    else
      redirect_to accommodation_comments_url
    end
  end

  def create
    unless @accommodation.commented_by?(current_user) || current_user.type != "user"
      @comment = @accommodation.comments.build(comment_params)
      @comment.user = current_user

      respond_to do |format|
        if @comment.save
          format.html { redirect_to accommodation_comments_path(@accommodation, @comment), notice: 'Comment was successfully created.' }
          format.json { render :show, status: :created, location: @comment }
        else
          format.html { render :new }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to comments_path
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy unless current_user.type == "manager"
    if @accommodation.present?
      redirect_to accommodation_comments_url(@accommodation), notice: "You can't destroy comment"
    else
      redirect_to comments_url, notice: 'Comment was successfully destroyed.'
    end
  end

  def grade
    unless @comment.posted_by?(current_user) || current_user.type != "user"
      grade = @comment.grades.build(value: params[:grade_value].to_f)
      grade.user = current_user
      grade.save

      redirect_to accommodation_comments_url(@accommodation)
    end
  end

  private

  def set_accommodation
    if params[:accommodation_id].present?
      @accommodation = Accommodation.find(params[:accommodation_id])
    end
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:grade, :text, :accommodation_id, :user_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment, url: url) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<% if @accommodation.present? %>
  <%= render 'form', comment: @comment, url: accommodation_comment_path(@accommodation, @comment) %>
<% else %>
  <%= render 'form', comment: @comment, url: comment_path(@comment) %>
<% end %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Grade</th>
      <th>Text</th>
      <th>Accommodation</th>
      <th>Posted by</th>
      <th>Grade</th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.average_grade %></td>
        <td><%= comment.text %></td>
        <td><%= link_to comment.accommodation.name, accommodation_path(comment.accommodation) %></td>
        <td><%= comment.user.email %></td>
        <% if comment.posted_by?(current_user) %>
          <% if @accommodation.present? %>
            <td><%= link_to 'Edit', edit_accommodation_comment_path(@accommodation, comment) %></td>
          <% else %>
            <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
          <% end %>
        <% end %>

        <% if comment.posted_by?(current_user) || current_user.type == "admin" %>
          <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

        <% unless comment.posted_by?(current_user) || current_user.type != "user" %>
          <td>
            <%= form_tag(grade_accommodation_comment_path(@accommodation, comment), id: "grade_form", method: :post) do %>
              <%= select_tag(:grade_value, options_for_select([1, 2, 3, 4, 5], current_user.grade(comment).to_i), disabled: (true if current_user.graded?(comment))) %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @accommodation.present? && !@accommodation.commented_by?(current_user) && current_user.type == "user" %>
  <%= link_to 'New Comment', new_accommodation_comment_path if current_user.type == "user" && @accommodation %>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment, url: accommodation_comments_path(@accommodation) %>

<%= link_to 'Back', accommodation_comments_path(@accommodation) %>