config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users

  scope module: 'admin', path: 'admin' do
    resources :countries
    resources :regions
    resources :places
    resources :accommodation_types
    get "/users", to: "users#index", as: "managers"
    post "/toggle_block_manager/:id", to: "users#toggle_block_manager", as: "toggle_block_manager"
  end

  resources :comments, :except => [:show, :new, :create]
  resources :room_reservations, :only => [:index, :show, :destroy]
  resources :accommodations do
    get "my", on: :collection, as: :my
    post "approve", on: :member, as: :approve
    resources :rooms, on: :member do
      resources :room_reservations, :except => [:index, :edit, :update, :show, :destroy]
    end
    resources :comments, on: :member do
      post "grade", on: :member, as: :grade
    end
  end
end

app/models/accommodation.rb
class Accommodation < ApplicationRecord
  belongs_to :place
  belongs_to :user
  belongs_to :accommodation_type

  has_many :rooms, :dependent => :destroy
  has_many :comments, :dependent => :destroy

  scope :all_except_owned_by, -> (user) { where.not(user: user) }
  scope :approved, -> { where(approved: true) }

  def self.top10
  end

  def self.wait_any?
    Accommodation.exists?(approved: false)
  end

  def owned_by?(owner)
    owner.id == user.id
  end

  def commented_by?(user)
    Comment.exists?(user: user, accommodation: self)
  end
end

app/models/accommodation_type.rb
class AccommodationType < ApplicationRecord
  has_many :accommodations, :dependent => :destroy
end

app/controllers/accommodations_controller.rb
class AccommodationsController < ApplicationController
  before_action :set_accommodation, only: [:show, :edit, :update, :destroy, :approve]
  before_action :set_places, except: [:index, :my, :destroy]
  before_action :set_accommodation_types, except: [:index, :my, :destroy]
  before_action :check_admin, only: [:approve]
  before_action :check_manager, only: [:new, :edit, :create, :update, :destroy, :my]
  before_action :check_user, only: []
  before_action :check_admin_or_user, only: [:index]
  before_action :check_blocked, only: [:create]

  def index
    @accommodations = if current_user.type == "manager"
                        current_user.accommodations
                      elsif current_user.type == "admin"
                        Accommodation.all
                      elsif current_user.type == "user"
                        Accommodation.approved
                      end
  end

  def show
  end

  def new
    @accommodation = Accommodation.new
  end

  def edit
  end

  def create
    @accommodation = current_user.accommodations.build(accommodation_params)

    if @accommodation.save
      ActionCable.server.broadcast(
        "accommodation_admin",
        body: "new accommodation"
      )
      redirect_to @accommodation, notice: 'Accommodation was successfully created.'
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @accommodation.update(accommodation_params)
        format.html { redirect_to @accommodation, notice: 'Accommodation was successfully updated.' }
        format.json { render :show, status: :ok, location: @accommodation }
      else
        format.html { render :edit }
        format.json { render json: @accommodation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @accommodation.destroy
    respond_to do |format|
      format.html { redirect_to accommodations_url, notice: 'Accommodation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def my
    @accommodations = current_user.accommodations
  end

  def approve
    @accommodation.approved = true
    @accommodation.save
    ActionCable.server.broadcast(
      "accommodation_manager#{@accommodation.user.id}",
      body: "approved"
    )
    redirect_to accommodations_url, notice: "#{@accommodation.name} is approved."
  end

  private

  def set_accommodation
    @accommodation = Accommodation.find(params[:id])
  end

  def set_places
    @places = Place.all
  end

  def set_accommodation_types
    @accommodation_types = AccommodationType.all
  end

  def check_admin
    ActionController::RoutingError.new("Not found") unless current_user.admin?
  end

  def check_manager
    ActionController::RoutingError.new("Not found") unless current_user.manager?
  end

  def check_user
    ActionController::RoutingError.new("Not found") unless current_user.user?
  end

  def check_admin_or_user
    check_admin || check_user
  end

  def check_blocked
    ActionController::RoutingError.new("Not found") if current_user.blocked?
  end

  def accommodation_params
    params.require(:accommodation).permit(:name, :description, :address, :average_grade, :latitude, :longitude, :image_url, :approved, :place_id, :accommodation_type_id)
  end
end

app/helpers/accommodations_helper.rb
module AccommodationsHelper
end

app/views/accommodations/_accommodations.html.erb
<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Name</th>
      <th>Rooms</th>
      <th>Description</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Image url</th>
      <th>Approved</th>
      <th>Place</th>
    </tr>
  </thead>

  <tbody>
    <% @accommodations.each do |accommodation| %>
      <tr>
        <td><%= accommodation.accommodation_type.name %>
        <td><%= accommodation.name %></td>
        <td><%= link_to accommodation.rooms.count, accommodation_rooms_path(accommodation) %></td>
        <td><%= accommodation.description %></td>
        <td><%= accommodation.address %></td>
        <td><%= accommodation.latitude %></td>
        <td><%= accommodation.longitude %></td>
        <td><%= accommodation.image_url %></td>
        <td><%= accommodation.approved %></td>
        <td><%= link_to accommodation.place.name, accommodation.place %></td>
        <td><%= link_to 'Show', accommodation %></td>
        <% if accommodation.owned_by?(current_user) %>
          <td><%= link_to 'Edit', edit_accommodation_path(accommodation) %></td>
          <td><%= link_to 'Destroy', accommodation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% if current_user.admin? && !accommodation.approved %>
          <td><%= link_to "Approve", approve_accommodation_path(accommodation), :method => :post%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/accommodations/_form.html.erb
<%= form_for(accommodation) do |f| %>
  <% if accommodation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(accommodation.errors.count, "error") %> prohibited this accommodation from being saved:</h2>

      <ul>
      <% accommodation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.select :accommodation_type_id, options_for_select(@accommodation_types.map { |type| [type.name, type.id] }, @accommodation_type), :prompt => "Select type" %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.number_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.number_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_area :image_url %>
  </div>

  <div class="field">
    <%= f.select :place_id, @places.map { |place| [place.name, place.id] }, :prompt => "Select place" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accommodations/edit.html.erb
<h1>Editing Accommodation</h1>

<%= render 'form', accommodation: @accommodation %>

<%= link_to 'Show', @accommodation %> |
<%= link_to 'Back', accommodations_path %>

app/views/accommodations/index.html.erb
<h2>Accommodations</h2>
<%= render "accommodations/accommodations" if @accommodations.present? %>

app/views/accommodations/my.html.erb
<h2>Your accommodations</h2>

<%= render "accommodations/accommodations" if @accommodations.present? %>

<%= link_to "New accommodation", new_accommodation_path unless current_user.blocked? %>

app/views/accommodations/new.html.erb
<h1>New Accommodation</h1>

<%= render 'form', accommodation: @accommodation %>

<%= link_to 'Back', accommodations_path %>

app/views/accommodations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @accommodation.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @accommodation.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @accommodation.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @accommodation.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @accommodation.longitude %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @accommodation.image_url %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @accommodation.approved %>
</p>

<p>
  <strong>Place:</strong>
  <%= link_to @accommodation.place.name, @accommodation.place %>
</p>

<p>
  <%= link_to "Comments", accommodation_comments_path(@accommodation) %>
</p>

<%= link_to 'Edit', edit_accommodation_path(@accommodation) %> |
<% if @accommodation.owned_by?(current_user) %>
  <%= link_to 'Back', my_accommodations_path %>
<% else %>
  <%= link_to 'Back', accommodations_path %>
<% end %>