config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users

  scope module: 'admin', path: 'admin' do
    resources :countries
    resources :regions
    resources :places
    resources :accommodation_types
    get "/users", to: "users#index", as: "managers"
    post "/toggle_block_manager/:id", to: "users#toggle_block_manager", as: "toggle_block_manager"
  end

  resources :comments, :except => [:show, :new, :create]
  resources :room_reservations, :only => [:index, :show, :destroy]
  resources :accommodations do
    get "my", on: :collection, as: :my
    post "approve", on: :member, as: :approve
    resources :rooms, on: :member do
      resources :room_reservations, :except => [:index, :edit, :update, :show, :destroy]
    end
    resources :comments, on: :member do
      post "grade", on: :member, as: :grade
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user.nil?
      @top_10 = Accommodation.top10
      render :welcome if current_user.nil?
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Welcome to booking</h1>
<ul>
  <% if current_user.type == "admin" %>
    <li><%= link_to "Places", places_path %></li>
    <li><%= link_to "Countries", countries_path %></li>
    <li><%= link_to "Regions", regions_path %></li>
    <li><%= link_to "Managers", managers_path %></li>
    <li><%= link_to "Accommodation types", accommodation_types_path %></li>
    <li><%= link_to "Accommodations", accommodations_path %></li>
    <li><%= link_to "Reservations", room_reservations_path %></li>
    <li><%= link_to "Comments", comments_path %></li>
  <% elsif current_user.type == "manager" %>
    <li><%= link_to "Your accommodations", my_accommodations_path %></li>
    <li><%= link_to "Customer reservations", room_reservations_path %></li>
    <li><%= link_to "Comments for your accommodations", comments_path %></li>
  <% elsif current_user.type == "user" %>
    <li><%= link_to "Accommodations", accommodations_path %></li>
    <li><%= link_to "Your reservations", room_reservations_path %></li>
    <li><%= link_to "Your comments", comments_path %></li>
  <% end %>
</ul>

app/views/home/welcome.html.erb
<h1>Welcome to Frankenstein</h2>