config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users

  scope module: 'admin', path: 'admin' do
    resources :countries
    resources :regions
    resources :places
    resources :accommodation_types
    get "/users", to: "users#index", as: "managers"
    post "/toggle_block_manager/:id", to: "users#toggle_block_manager", as: "toggle_block_manager"
  end

  resources :comments, :except => [:show, :new, :create]
  resources :room_reservations, :only => [:index, :show, :destroy]
  resources :accommodations do
    get "my", on: :collection, as: :my
    post "approve", on: :member, as: :approve
    resources :rooms, on: :member do
      resources :room_reservations, :except => [:index, :edit, :update, :show, :destroy]
    end
    resources :comments, on: :member do
      post "grade", on: :member, as: :grade
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :accommodation
  has_many :room_reservations, :dependent => :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_accommodation
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = @accommodation.rooms
  end

  def show
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = @accommodation.rooms.build(room_params)

    if @room.save
      redirect_to accommodation_room_url(@accommodation, @room), notice: 'Room was successfully created.'
    else
      render :new
    end
  end

  def update
    if @room.update(room_params)
      redirect_to accommodation_room_url(@accommodation, @room), notice: 'Room was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to accommodation_rooms_url, notice: 'Room was successfully destroyed.'
  end

  private
  def set_room
    @room = Room.find(params[:id])
  end

  def set_accommodation
    @accommodation = Accommodation.find(params[:accommodation_id])
  end

  def room_params
    params.require(:room).permit(:room_number, :bed_count, :description, :price_per_night, :accommodation_id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(room, url: url) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_number %>
    <%= f.number_field :room_number %>
  </div>

  <div class="field">
    <%= f.label :bed_count %>
    <%= f.number_field :bed_count %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price_per_night %>
    <%= f.text_field :price_per_night %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room, url: accommodation_room_path(@accommodation, @room) %>

<%= link_to 'Show', accommodation_room_path(@accommodation, @room) %> |
<%= link_to 'Back', accommodation_rooms_path(@accommodation) %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Accommodation</th>
      <th>Room number</th>
      <th>Bed count</th>
      <th>Description</th>
      <th>Price per night</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= link_to room.accommodation.name, accommodation_path(room.accommodation) %></td>
        <td><%= room.room_number %></td>
        <td><%= room.bed_count %></td>
        <td><%= room.description %></td>
        <td><%= room.price_per_night %></td>
        <td><%= link_to 'Show', accommodation_room_path(@accommodation, room) %></td>
        <% if @accommodation.owned_by?(current_user) %>
          <td><%= link_to 'Edit', edit_accommodation_room_path(@accommodation, room) %></td>
          <td><%= link_to 'Destroy', accommodation_room_path(@accommodation, room), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_accommodation_room_path(@accommodation) if @accommodation.owned_by?(current_user) && !current_user.blocked?%>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room, url: accommodation_rooms_path(@accommodation) %>

<%= link_to 'Back', accommodation_rooms_path(@accommodation) %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room number:</strong>
  <%= @room.room_number %>
</p>

<p>
  <strong>Bed count:</strong>
  <%= @room.bed_count %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>Price per night:</strong>
  <%= @room.price_per_night %>
</p>

<p>
  <strong>Accommodation:</strong>
  <%= link_to @room.accommodation.name, accommodation_path(@room.accommodation) %>
</p>

<% if current_user.type == "user" %>
  <p>
    <strong><%= link_to "Reserve", new_accommodation_room_room_reservation_path(@accommodation, @room) %></strong>
  </p>
<% end %>

<%= link_to 'Edit', edit_accommodation_room_path(@accommodation, @room) if @accommodation.owned_by?(current_user) %> |
<%= link_to 'Back', accommodation_rooms_path(@accommodation) %>